<h1>Page de gestion des adresses IP</h1>
<br /><br /><br />
<h2>Possibilités d'afficher toutes les adresses par VLAN et Zone d'adresse</h2>
<h2>Ainsi que de faire des recherches par nom de machine, profil et adresse ip</h2>
<h2>Possibilité d'ajouter/supprimer des VLAN dans la base de données</h2>
<h2>Possibilité de supprimer les adresses ip qui ne sont pas modifiées par Abitop</h2>
<h3>Historisation des ajouts et des suppressions</h3>