/**
 * VUE STRUCTURELLE PRINCIPALE
 *
 * Nom Fichier: Error
 * Auteur:	Emmanuel ROY <acksop@yahoo.fr>
 *
 *
 * Description developpeur:
 *
 *C'est dans cette partie que l'on écrit la page centrale du body 
 * contenu entre le <header>l'en-tête HTML5 de la page</header>
 * et le <footer>le pied de page HTML5</footer>
 * qui sont normalement communes a toutes les pages
 *
 * Il est possible que cette partie soit traiter en AJAX afin que les chargements
 * entre les pages soient plus fluides
 * 
 * Description utilisateur:
 *
 *
 *
 * 
 *
 *
 */
<h1>ERREUR poo_v1</h1>
