<div class="meny">
    <h2>VLAN Experiments</h2>
    <ul>
        <li><a href="<?php echo PATH_URL; ?>vlan-zone+">Par VLAN</a><a href="<?php echo PATH_URL; ?>vlan-zone">[+]</a></li>
        <li><a href="<?php echo PATH_URL; ?>ip-zone+">Par Zone d'adresse</a><a href="<?php echo PATH_URL; ?>ip-zone">[+]</a></li>
        <li><a href="<?php echo PATH_URL; ?>vlan-add">Ajouter un VLAN</a></li>
        <li><a href="<?php echo PATH_URL; ?>search">Recherche</a></li>
    </ul>
</div>

<div class="meny-arrow"></div>
