<!doctype html>

<html lang="fr">

<head>
  <meta charset="utf-8">

  <title><?php echo $page_title; ?></title>
  <meta name="description" content= "<?php echo $description; ?>" >

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

    <!-- Les favicons -->
    <link rel="apple-touch-icon" href="<?php echo PATH_URL; ?>apple-touch-icon.png">
    <link rel="icon" href="<?php echo PATH_URL; ?>favicon.png" />

  <?php include LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."top-css.phtml"; ?>

</head>
