<?php
define('LAYOUT_TEMPLATE',dirname(__FILE__).DIRECTORY_SEPARATOR.'include'.DIRECTORY_SEPARATOR.'standart');


 echo LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."head.pthml"


<body>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  

  <header>
   echo LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."header.pthml"
  </header>


   echo LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."body.pthml" 

  <footer>
		echo LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."header.pthml"
  </footer>


  <!-- JavaScript at the bottom for fast page loading -->
	echo LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."bottom-javascript.pthml"
  
</body>
</html>
