<?php
define('LAYOUT_TEMPLATE',dirname(__FILE__).DIRECTORY_SEPARATOR.'include'.DIRECTORY_SEPARATOR.'standard');

require LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."head.phtml";
?>


<body>

  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
  
  <?php include LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."header.phtml"; ?>

  <div class="contents">
    <?php include LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."body.phtml"; ?>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="dnsModal" tabindex="10" role="dialog" aria-labelledby="dnsModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="dnsModalLabel"></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                  <div id="contentDNS"></div>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Clore</button>
              </div>
          </div>
      </div>
  </div>

  <?php include LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."footer.phtml"; ?>


  <!-- JavaScript at the bottom for fast page loading -->
  <?php include LAYOUT_TEMPLATE.DIRECTORY_SEPARATOR."bottom-javascript.phtml"; ?>
  
</body>
</html>
